name: Build and Deploy Clien to AWS Amplify

on:
  push:
    branches:
      - main
    paths:
      - "Frontend/**"
      - ".github/workflows/client_deploy.yaml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
