name: Build and Deploy Client to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - "Frontend/**"
      - ".github/workflows/client_deploy.yaml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Step 4: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Step 5: Configure Docker for Google Cloud Registry
      - name: Configure Docker to use the Google Cloud Registry
        run: gcloud auth configure-docker

      # Step 6: Build the Docker image
      - name: Build the Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend:latest -f Frontend/Dockerfile Frontend

      # Step 7: Push the Docker image to GCP Container Registry
      - name: Push the Docker image to GCP Container Registry
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend:latest

      # Step 8: Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy frontend \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --port 8080
