name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Configure Docker to use the Google Cloud Registry
      run: gcloud auth configure-docker

    - name: Build the Docker image
      run: |
        docker build -t ${{ secrets.GCP_PROJECT_ID }}/${{ secrets.DOCKER_IMAGE }}:latest .

    - name: Push the Docker image to GCP Container Registry
      run: |
        docker push ${{ secrets.GCP_PROJECT_ID }}/${{ secrets.DOCKER_IMAGE }}:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ secrets.DOCKER_IMAGE }} \
          --image ${{ secrets.GCP_PROJECT_ID }}/gcp-automation:latest \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --port 8080